### ISSUE TITLE
Is pipelining possible with RipeRedis?

### ISSUE THREAD

**Issue by mansoor-s** [iph0/AnyEvent-Redis-RipeRedis#2]
Thank you for making this redis client!

Is it possible to do pipelining with RipeRedis? http://redis.io/topics/pipelining
Pipelining will allow for **significant** performance improvements. If it is currently not possible, is it on the roadmap to be added?

**Comment by iph0** [comment]
Non-blocking mode already means that you working in pipeline mode with one exception - writes in socket are not grouped by default. To resolve this issue you must set `autocork` option to true value.

```
my $redis = AnyEvent::Redis::RipeRedis->new(
  handle_params => {
    autocork => 1,
  },
  ...
);
```

When enabled, writes will always be queued till the next event loop iteration. Then you can just write:

$redis->set( 'foo1', 'bar1', sub { ... } );
$redis->set( 'foo2', 'bar2', sub { ... } );
$redis->set( 'foo3', 'bar3', sub { ... } );
...

See AnyEvent::Handle for more information.
